# Generated by Django 4.2.3 on 2023-08-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_post_comments_alter_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
