# Generated by Django 4.2.3 on 2023-08-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
