# Generated by Django 4.2.3 on 2023-08-11 16:07

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_remove_post_comments_comment_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=100, verbose_name=network.models.User),
        ),
    ]
