# Generated by Django 4.2.3 on 2023-08-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
