# Generated by Django 4.2.3 on 2023-08-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notificationKey',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
