# Generated by Django 4.2.3 on 2023-08-17 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_profile_notificationkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
