# Generated by Django 4.2.3 on 2023-09-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0026_notificationkey_remove_profile_notificationkey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notificationKeys',
        ),
        migrations.DeleteModel(
            name='notificationKey',
        ),
    ]
