# Generated by Django 4.2.3 on 2023-12-23 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0032_onlineuser_chatroom_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='member',
            new_name='members',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='type',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='chatType',
            field=models.CharField(default='DM', max_length=6),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(to='network.chatmessage'),
        ),
        migrations.AddField(
            model_name='user',
            name='lastMsgRead',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='roomId',
            field=models.CharField(max_length=255),
        ),
    ]
