# Generated by Django 4.2.3 on 2023-12-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0033_rename_member_chatroom_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastMsgRead',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
