# Generated by Django 4.2.3 on 2023-12-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0034_chatmessage_read_alter_user_lastmsgread'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_id',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
