# Generated by Django 4.2.3 on 2023-12-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0035_user_registration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
